/*
 * This Java source file was generated by the Gradle 'init' task.
 */

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

package com.mparang.azlib;

public class LibraryTest {
//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
    public LibraryTest() {

    }
    public static void main(String ...args) {
        AZData data = new AZData();
        data
            .add("k1", 1)
            .add("K2", "v2")
            .add(
                "k3",
                new AZData()
                    .add("k11", "v11")
                    .add("k12.1", 12)
                    .add("k12.2", 12.233)
                    .add("k13", true)
                    .add("k14", false)
                    .add("k15", null)
                    .add("k16", new AZData().add("k16.1", "Hello"))
            )
            .add("k4", '/')
            .add("k4", 'c')
            .add("k5", "\"Judy\"! /^^/~ \\gg")
            .add("l1", new AZList()
                .add(
                    new AZData()
                        .add("l1k1", "l1v1")
                )
                .add(
                    new AZData()
                        .add("l1k2", "l1v2")
                )
                .add(
                    new AZData()
                        .add("l1k3", "l1v3")
                )
            )
            .add("k5", "k5");
        System.out.println(data);
        Object[] k5s = data.getAll("k5");
        for (int cnti = 0; cnti < k5s.length; cnti++) {
            System.out.println("k5s.#" + cnti + ": " + k5s[cnti]);
        }
        System.out.println("k5: " + data.get("k5"));
        System.out.println("seek k3, k13: " + data.seek("k3", "k12.2"));
        System.out.println("seek l1: " + data.seek("l1"));
        System.out.println("seek l1, 0: " + data.seek("l1", 0));
        System.out.println("seek l1, Seek.LAST: " + data.seek("l1", AZList.Seek.LAST));
        System.out.println("seek l1, Seek.LAST, l1k3: " + data.seek("l1", AZList.Seek.LAST, "l1k3"));
        //
        AZList list = new AZList().add(data).add(data);
        System.out.println("list:" + list);
        //
        data.attribute()
            .add("ecma_array", true)
            .add("test", "v1");
        System.out.println(data.attribute());
        String[] keys = data.attribute().getAllKeys();
        for (String key: keys) {
            System.out.println("attr - key:" + key);
        }
        System.out.println("attr:" + data.attribute());
    }
}
